acme_admin:
    resource: "@AcmeAdminBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

acme_app:
    resource: "@AcmeAppBundle/Resources/config/routing.yml"
    prefix:   /

#app:
 #   resource: @AppBundle/Controller/
  #  type:     annotation
