acme_app:
    resource: "@AcmeAppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /