acme_blog_homepage:
    path:     /
    defaults: { _controller: AcmeBlogBundle:Default:index }

acme_blog_article:
    path:   /article/{alias}
    defaults: { _controller: AcmeBlogBundle:Default:article }

acme_blog_articles:
    path:   /articles
    defaults: { _controller: AcmeBlogBundle:Default:articles }

acme_blog_news:
    path:   /news
    defaults: { _controller: AcmeBlogBundle:Default:news }

acme_blog_impressum:
    path:   /impressum
    defaults: { _controller: AcmeBlogBundle:Default:impressum }

acme_blog_jsonallarticles:
    path:   /jsonallarticles
    defaults: { _controller: AcmeBlogBundle:Default:jsonallarticles }

acme_blog_kontakt:
    path:   /kontakt
    defaults: { _controller: AcmeBlogBundle:Default:kontakt }

acme_blog_mannschaft:
    path:   /mannschaft
    defaults: { _controller: AcmeBlogBundle:Default:mannschaft }

acme_blog_reports:
    path:   /spielberichte
    defaults: { _controller: AcmeBlogBundle:Default:reports }

acme_blog_jsonallreports:
    path:   /jsonallreports
    defaults: { _controller: AcmeBlogBundle:Default:jsonallreports }

acme_blog_trainingszeiten:
    path:   /trainingszeiten
    defaults: { _controller: AcmeBlogBundle:Default:trainingszeiten }
    
acme_blog_events:
    path:   /termine
    defaults: { _controller: AcmeBlogBundle:Default:events }

acme_blog_singleevent:
    path:   /termin/preview/{id}
    defaults: { _controller: AcmeBlogBundle:Default:singleevent }

acme_blog_event:
    path:   /termin/{alias}
    defaults: { _controller: AcmeBlogBundle:Default:event }

acme_blog_jsonevents:
    path:   /jsonevents
    defaults: { _controller: AcmeBlogBundle:Default:jsonevents }


##
## Admin routes
##

acme_blog_admin:
    path:   /admin
    defaults: { _controller: AcmeAdminBundle:Admin:admin }

acme_blog_login:
    path:   /login
    defaults: { _controller: AcmeBlogBundle:Security:login }

acme_blog_logincheck:
    path:   /login_check
    defaults: { _controller: AcmeBlogBundle:Security:login_check }

logout:
    path: /logout