acme_blog_homepage:
    path:     /
    defaults: { _controller: AcmeBlogBundle:Default:index }
    
acme_blog_user:
    path:     /show/{id}
    defaults: { _controller: AcmeBlogBundle:Default:show }

acme_blog_article:
    path:   /article/{alias}
    defaults: { _controller: AcmeBlogBundle:Default:article }
    
acme_blog_articles:
    path:   /articles
    defaults: { _controller: AcmeBlogBundle:Default:articles }
    
acme_blog_news:
    path:   /news
    defaults: { _controller: AcmeBlogBundle:Default:news }

acme_blog_impressum:
    path:   /impressum
    defaults: { _controller: AcmeBlogBundle:Default:impressum }
    
acme_blog_jsonallarticles:
    path:   /jsonallarticles
    defaults: { _controller: AcmeBlogBundle:Default:jsonallarticles }

acme_blog_kontakt:
    path:   /kontakt
    defaults: { _controller: AcmeBlogBundle:Default:kontakt }
    
acme_blog_mannschaft:
    path:   /mannschaft
    defaults: { _controller: AcmeBlogBundle:Default:mannschaft }
   
##
## Admin routes
##   

acme_blog_admin:
    path:   /admin
    defaults: { _controller: AcmeAdminBundle:Admin:admin }
    
acme_blog_login:
    path:   /login
    defaults: { _controller: AcmeBlogBundle:Security:login }
    
acme_blog_logincheck:
    path:   /admin/login_check
    defaults: { _controller: AcmeBlogBundle:Security:login_check }
    
logout:
    path: /admin/logout